[theme]
base = "light"
primaryColor = "#0b3158"
backgroundColor = "#e9edf0"
secondaryBackgroundColor = "#f4f5f6"
textColor = "#172b3d"
font = "sans-serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[server]
showEmailPrompt = false
